name: Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release-mac-aarch64:
    name: release mac aarch64
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build CSS
      run: npm run build:css
    - name: Build TS
      run: npm run build:esbuild
    - name: Build static
      run: npm run build:static
    #- name: Run tests
    #  run: cargo test
    - name: Make sure target is installed for Rust
      run: rustup target add aarch64-apple-darwin
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --release --target=aarch64-apple-darwin
    - name: Compress
      run: zip -9r wallowa-aarch64-apple-darwin-${{ github.ref_name }}.zip target/release/wallowa

  release-mac-x86_64:
    name: release mac x86_64
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build CSS
      run: npm run build:css
    - name: Build TS
      run: npm run build:esbuild
    - name: Build static
      run: npm run build:static
    #- name: Run tests
    #  run: cargo test
    - name: Make sure target is installed for Rust
      run: rustup target add x86_64-apple-darwin
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --release --target=x86_64-apple-darwin
    - name: Compress
      run: zip -9r wallowa-x86_64-apple-darwin-${{ github.ref_name }}.zip target/release/wallowa
