name: update-website

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  update-website:
    name: update-website
    runs-on: ubuntu-latest
    permissions:
      contents:write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Rebase website-production branch from main
        run: |
          git pull
          git checkout website-production
          git pull --rebase origin main
          git push origin website-production
